### ISSUE TITLE
Jellyfin parser not working

### ISSUE THREAD

**Issue by woolmonkey** [crowdsecurity/hub#1046]
Hello I added LePresidente/jellyfin and it does not parse any logs.  I have tried a failed attempt and nothing.  I am running docker and made the change that was mentioned in the documents.

Parser Metrics:
╭──────────────────────────────────┬──────┬────────┬──────────╮
│             Parsers              │ Hits │ Parsed │ Unparsed │
├──────────────────────────────────┼──────┼────────┼──────────┤
│ LePresidente/jellyfin-logs       │ 2    │ -      │ 2        │
│ child-LePresidente/jellyfin-logs │ 2    │ -      │ 2        │
│ crowdsecurity/non-syslog         │ 2    │ 2      │ -        │
╰──────────────────────────────────┴──────┴────────┴──────────╯
```
[2024-05-19 05:41:14.201 -06:00] [INF] [3] Jellyfin.Server.Implementations.Users.UserManager: Authentication request for dfsd has been denied (IP: 2001:56a:f849:ac00:5151:2bd9:843f:73f3).
[2024-05-19 05:41:14.202 -06:00] [ERR] [3] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request: Invalid username or password entered. URL POST /Users/authenticatebyname.
```

```
pattern_syntax:
  JELLYFIN_CUSTOMUSER: "(%{EMAILADDRESS}|%{USERNAME})"
  JELLYFIN_CUSTOMDATE: "%{YEAR}-%{MONTHNUM}-%{MONTHDAY} %{HOUR}:%{MINUTE}:%{SECOND}"
nodes:
  - grok:
      pattern: '\[%{JELLYFIN_CUSTOMDATE:timestamp}.*\].*Authentication request for "%{JELLYFIN_CUSTOMUSER:username}" has been denied \(IP: "%{IP:source_ip}"\).*'
      apply_on: message
      statics:
        - meta: log_type
          value: jellyfin_failed_auth
```
