### ISSUE TITLE
http-sqli-probbing-detection is not detecting this kind of sql injection

### ISSUE THREAD

**Issue by ShaggyGS** [crowdsecurity/hub#1241]
Hello, we had a massive attack today to this kind of endpoints, that contains sql injection attempt:

```
54.197.194.* - - [05/Feb/2025:05:27:56 +0100] "GET /index.php?site=forum_topic+%2F%2A%2A%2F%27%2F%2A%2A%2FAND%2F%2A%2A%2F%28SELECT%2F%2A%2A%2F5808%2F%2A%2A%2FFROM%28SELECT%2F%2A%2A%2FCOUNT%28%2A%29%2CCONCAT%280x4b6c3078%2C%28SELECT%2F%2A%2A%2FIFNULL%28CAST%28COUNT%28schema_name%29%2F%2A%2A%2FAS%2F%2A%2A%2FNCHAR%29%2C0x20%29%2F%2A%2A%2FFROM%2F%2A%2A%2FINFORMATION_SCHEMA.SCHEMATA%29%2C0x34417a48%2CFLOOR%28RAND%280%29%2A2%29%29x%2F%2A%2A%2FFROM%2F%2A%2A%2FINFORMATION_SCHEMA.PLUGINS%2F%2A%2A%2FGROUP%2F%2A%2A%2FBY%2F%2A%2A%2Fx%29a%29%23%2F%2A%2A%2FXJhW&topic=20 HTTP/1.1" 200 465 "-" "Wget/1.9 cvs-stable (Red Hat modified)"
54.197.194.* - - [05/Feb/2025:05:27:56 +0100] "GET /index.php?site=forum_topic+%2F%2A%2A%2F%27%2F%2A%2A%2FAND%2F%2A%2A%2F%28SELECT%2F%2A%2A%2F5808%2F%2A%2A%2FFROM%28SELECT%2F%2A%2A%2FCOUNT%28%2A%29%2CCONCAT%280x714c5973%2C%28SELECT%2F%2A%2A%2FIFNULL%28CAST%28COUNT%28schema_name%29%2F%2A%2A%2FAS%2F%2A%2A%2FNCHAR%29%2C0x20%29%2F%2A%2A%2FFROM%2F%2A%2A%2FINFORMATION_SCHEMA.SCHEMATA%29%2C0x6a546841%2CFLOOR%28RAND%280%29%2A2%29%29x%2F%2A%2A%2FFROM%2F%2A%2A%2FINFORMATION_SCHEMA.PLUGINS%2F%2A%2A%2FGROUP%2F%2A%2A%2FBY%2F%2A%2A%2Fx%29a%29%23%2F%2A%2A%2FNp6M&topic=20 HTTP/1.1" 200 463 "-" "Wget/1.9 cvs-stable (Red Hat `modified)"
```

Would be possible to expand your scenario to catch these attacks too? Or should we create our own scenario for this? Notice the attacker changed the last few characters at the end of the URL GET "site" parameter...

Thank you!

**Comment by LaurenceJJones** [comment]
Hey 👋🏻 

The sqli-probing is very basic detect for SQLi probing, in my opinion if you want to provide a wide coverage I suggest to use a WAF solution as detecting sqli after the fact means there a risk that it could of executed plus if we provide a bigger list to the rule datafile then it only going to make the rule very very slow.

Here an example rule you could run with our [appsec component](https://docs.crowdsec.net/docs/next/appsec/intro)

```
name: my/sqli-index-site-injection
description: "Detect SQLi in site query"
rules:
  - and:
    - zones:
      - METHOD
      match:
        type: equals
        value: GET
    - zones:
      - URI
      transform:
      - lowercase
      match:
        type: contains
        value: /index.php
    - zones:
      - ARGS
      transform:
      - lowercase
      variables:
      - site
      match:
        type: libinjectionSQL

labels:
  type: exploit
  service: http
  confidence: 3
  spoofable: 0
  behavior: "http:exploit"
```

which will generate the following modsecurity rule

```
SecRule REQUEST_METHOD "@streq GET" "id:2810586329,phase:2,deny,log,msg:'my/sqli-index-site-injection',tag:'crowdsec-my/sqli-index-site-injection',chain"
SecRule REQUEST_FILENAME "@contains /index.php" "id:1313113907,phase:2,deny,log,msg:'my/sqli-index-site-injection',tag:'crowdsec-my/sqli-index-site-injection',t:lowercase,chain"
SecRule ARGS_GET:site "@detectSQLi " "id:3815296623,phase:2,deny,log,msg:'my/sqli-index-site-injection',tag:'crowdsec-my/sqli-index-site-injection',t:lowercase"
```

it wont be 100% coverage but it will be better coverage than relying solely on the sqli scenario.
