### ISSUE TITLE
[LePresidente/authelia-logs] Not parsing missing user errors

### ISSUE THREAD

**Issue by AndreiArdelean1** [crowdsecurity/hub#1268]
When an authentication attempt is made with a non-existing user, the message isn't parsed.

The error from authelia logs is:
```
time="2025-01-01T00:00:00+00:00" level=error msg="Error occurred getting details for user with username input 'MISSING_USER' which usually indicates they do not exist" error="user not found" method=POST 
```

Adding this parser to `nodes` solves the issue:
```
  ## Detect msg contains authentication attempt to parse out user info
path=/api/firstfactor remote_ip=192.168.0.1
  - grok:
      pattern: "Error .* getting details for user .* username input '%{AUTHELIA_USER:user}'.*" 
      expression: evt.Unmarshaled.authelia.msg
    statics:
      - meta: log_type
        value: auth_failed
```
