### ISSUE TITLE
Caddy, spamming warning messages: failed to run RunTimeValue interface conversion

### ISSUE THREAD

**Issue by doums** [crowdsecurity/hub#1331]
Hi, since few days ago, I have this message in logs, spamming

```
time="2025-04-12T22:31:00+02:00" level=warning msg="failed to run RunTimeValue : interface conversion: interface {} is nil, not string (1:1)\n | Split(evt.Unmarshaled.caddy.request.remote_addr, ':')[0]\n | ^" id=little-shadow name=crowdsecurity/caddy-logs stage=s01-parse
```

I'm using `crowdsecurity/caddy-logs` to parse my caddy JSON logs. It's up-to-date (1.0). Logs are ingested via simple file acquisition:
```
source: file
filenames:
  - /var/log/caddy/*.log
labels:
 type: caddy
```

The caddy logger is `http.log.access.http-logger` and logs format is JSON.
I'm not sure if this is due to some misconfiguration from my side or actually a bug in the parser?

Versions

```
version: v1.6.8-f209766e
Codename: alphaga
BuildDate: 2025-03-25_15:53:20
GoVersion: 1.24.1
Platform: docker
libre2: C++
User-Agent: crowdsec/v1.6.8-f209766e-docker
Constraint_parser: >= 1.0, <= 3.0
Constraint_scenario: >= 1.0, <= 3.0
Constraint_api: v1
Constraint_acquis: >= 1.0, < 2.0
Built-in optional components: cscli_setup, datasource_appsec, datasource_cloudwatch, datasource_docker, datasource_file, datasource_http, datasource_journalctl, datasource_k8s-audit, datasource_kafka, datasource_kinesis, datasource_loki, datasource_s3, datasource_syslog, datasource_victorialogs, datasource_wineventlog
```

**Comment by superbunny54** [comment]
Hi I have the same issue here I can provide infos about my setup:
here is the Caddyfile I used:
```
# Global options block
{
  log defaults {
    output file /var/log/caddy/caddy.log
    level INFO
  }
  crowdsec {
      api_url http://crowdsec:8080
      api_key {$CROWDSEC_LAPI_KEY}
      ticker_interval 15s
  }
}

# Define reusable snippets
(common) {
    @country_fr maxmind_geolocation {
        db_path /geolite2/GeoLite2-Country_20250228/GeoLite2-Country.mmdb
        allow_countries FR # can add more, space separated
    }
    @white_ip remote_ip 192.168.1.0/24 
    # 192.168.1.0/24 lan

    # if ip is whitelisted then bypass crowdsec
    route @white_ip {
        reverse_proxy {args[0]}
    }
    # if not whitlisted but IP is FR then go through crowdsec
    route @country_fr {
        crowdsec
        reverse_proxy {args[0]}
    }
    ## if not FR and not white then access denied
    route {
        respond 403 {
            body "Access denied"
        }
    }
    # format logs for crowdsec
    log defaults {
      output file /var/log/caddy/access.log
      format json
    }
}

# Services
my.website.com {
    import common http://192.168.1.x:x
}
```

my docker-compose.yaml
```yaml
services:
  caddy:
    build:
      context: .
    restart: unless-stopped
    user: 1000:1000
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data-2:/data
      - caddy_config-2:/config
      - ./geolite2:/geolite2:ro
      - ./caddy_logs/:/var/log/caddy/
    environment:
      - CROWDSEC_LAPI_KEY=<redacted>
    # Add caps to bind to privileged ports while running as non-root
    cap_add:
      - NET_BIND_SERVICE
    depends_on:
      crowdsec:
        condition: service_healthy
        restart: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2019/config/"]
      interval: 30s
      timeout: 10s
      retries: 3

  crowdsec:
    container_name: crowdsec
    image: crowdsecurity/crowdsec:latest
    restart: always
    environment:
      COLLECTIONS: "crowdsecurity/caddy"
    volumes:
      - ./crowdsec/config/:/etc/crowdsec/
      - ./caddy_logs/:/var/log/caddy/:ro
      - ./crowdsec/db/:/var/lib/crowdsec/data/
    healthcheck:
      test: ["CMD-SHELL", "wget --spider --quiet --tries=1 --timeout=5 http://localhost:8080/health > /dev/null 2>&1 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  caddy_data-2:
  caddy_config-2:
  ```
  and the Dockerfile even tho it should not matter since it is not bouncer related:

```
# Step 1: Use Go to build Caddy with the CrowdSec plugin
FROM caddy:builder AS builder
RUN xcaddy build \
    --with github.com/hslatman/caddy-crowdsec-bouncer/http \
    --with github.com/porech/caddy-maxmind-geolocation

# Step 2: Use the official Caddy image as the base and copy over the custom Caddy build
FROM caddy:latest
COPY --from=builder /usr/bin/caddy /usr/bin/caddy

# Switch to root temporarily to set permissions
USER root

# Create caddy user (BusyBox syntax)
RUN addgroup -S -g 1000 caddy && \
    adduser -S -u 1000 -G caddy caddy

# Create required directories with proper permissions
RUN mkdir -p /data/caddy/certificates && \
    mkdir -p /data/caddy/locks && \
    mkdir -p /config/caddy && \
    mkdir -p /var/log/caddy && \
    chown -R caddy:caddy /data && \
    chown -R caddy:caddy /config && \
    chown -R caddy:caddy /var/log/caddy

# Switch back to non-root user
USER caddy
```
