### ISSUE TITLE
Parser "gitea-logs" does't parse failed login with email

### ISSUE THREAD

**Issue by freaky-m0** [crowdsecurity/hub#1352]
**Describe the bug**
I'm not sure if this is the right place for an issue with a community parser but here is my problem: I use the gitea collection with forgejo and failed logins (not existing e-mail) won't get parsed. I'm not sure if this only applies to forgejo, because I don't have a gitea installation.

It's this parser: `parsers/s01-parse/LePresidente/gitea-logs.yaml`

**To Reproduce**
login to forgejo/gitea with wrong e-mail

**Expected behavior**
Parsed failed login attempt.

**Screenshots**
none

**Additional context**
I added this to my local gitea-logs.yaml, but I'm not 100% sure if this is completely correct / enough. I see parsed log events though. 

```
  - grok:
      pattern: "^%{GITEA_CUSTOMDATE:timestamp}.*?Failed authentication attempt for %{GITEA_CUSTOMUSER:username} from %{IP:remote_ip}:%{NUMBER:remote_port}.* Email address does not exist.*"
      apply_on: message
      statics:
        - meta: log_type
          value: gitea_failed_auth

```

the log entry looks like this:
`2025/04/27 11:40:37 ...ers/web/auth/auth.go:221:SignInPost() [W] Failed authentication attempt for aa@bb.net from 1.2.3.4:0: Email address does not exist [email: aa@bb.net]`
