### ISSUE TITLE
Whitelist Ezoic

### ISSUE THREAD

**Issue by LtSich** [crowdsecurity/hub#145]
Ezoic provide ads service but in a special way.
To work you need to use their proxy server, then the IP that you server will see are the ezoic IP address.
If you block those IPs your site will not work anymore.

To avoid that this is a whitelist parser for ezoic.

```
name: ezoic/whitelist
description: "Whitelist IP Ezoic"
whitelist:
  reason: "Servers Ezoic"
  expression:
    - "any(File('ezoic_ips.txt'), { IpInRange(evt.Meta.source_ip ,#)})"
data:
  - source_url: https://client.siegler-informatique.fr/ezoic_ips.txt
    dest_file: ezoic_ips.txt
    type: string
```

The orignal file with the IP list can be find here : https://support.ezoic.com/kb/article/how-to-fix-origin-errors
Be carefull, adding so much IPs on crowdsec will slow down the start / stop process.
But outside that everything work fine.
