### ISSUE TITLE
Authelia collection is ignoring or?

### ISSUE THREAD

**Issue by SAOPP** [crowdsecurity/hub#428]
Hi!

I got this line - after update or upgrade hub... And only unparsed lines for authelia also, is that normal?

`time="04-04-2022 11:52:38 PM" level=info msg="Ignoring file /etc/crowdsec/hub/collections/LePresidente/authelia.yml of type collections"`

Here is my `acquis.yaml 
`
```
filenames:
  - /var/log/traefik/*
labels:
  type: traefik

---
filenames:
  - /var/log/authelia.log
labels:
  type: authelia
```
