### ISSUE TITLE
CrowdSec has a huge Matrix problem

### ISSUE THREAD

**Issue by ethindp** [crowdsecurity/hub#547]
Okay, so... Crowdsec has a major problem with Matrix. I just had to put my entire CrowdSec installation into simulation mode globally because it keeps generating a huge number of false positives and effectively isolating my server from the internet. What's the best way of going about fixing this problem? I need to whitelist a few subdomains, then explicitly allow port 8448 (and probably a bunch of others). I could just uninstall all the http-based scenarios, but I really don't want to do that because those are actually useful, just not in their current configuration.

**Comment by buixor** [comment]
Hello,

Are you able to share logs generated by matrix ? A list of the scenarios that triggered false positives might be useful too :)

A possibility is to have some matrix-specific whitelists when it is relevant :)

**Comment by LaurenceJJones** [comment]
link to task #575

**Comment by tetsumaki** [comment]
Same here from my synapse server with:
- crowdsecurity/http-probing (frequently)
- http-crawl-non_statics (rarely)

It is normal to have frequent 404 errors.

cscli alertes inspect -d id:

```
- Date: 2022-11-21 16:51:07 +0000 UTC
+-----------------+------------------------------------------------------------------------------+
|       KEY       |                                    VALUE                                     |
+-----------------+------------------------------------------------------------------------------+
| ASNNumber       |                                                                         3215 |
| ASNOrg          | Orange                                                                       |
| IsInEU          | true                                                                         |
| IsoCode         | FR                                                                           |
| SourceRange     | 92.184.96.0/19                                                               |
| datasource_path | /var/lib/caddy/log/matrix.domain.tld.log                                     |
| datasource_type | file                                                                         |
| http_path       | /_matrix/media/r0/preview_url?url=https%3A%2F%2Fapt-cacher.net.xxx.fr%3A3142 |
| http_status     |                                                                          404 |
| http_user_agent | Element/1.5.7 (Gigaset GS290;                                                |
|                 | Android 10; e_GS290-user                                                     |
|                 | 10 QQ3A.200805.001                                                           |
|                 | eng.root.20221031.181139                                                     |
|                 | dev-keys,dev-release; Flavour                                                |
|                 | FDroid; MatrixAndroidSdk2                                                    |
|                 | 1.5.7)                                                                       |
| http_verb       | GET                                                                          |
| log_type        | http_access-log                                                              |
| service         | http                                                                         |
| source_ip       | 92.184.xxx.x                                                                 |
| target_fqdn     | matrix.domain.tld                                                            |
| timestamp       | 2022-11-21T16:51:07Z                                                         |
+-----------------+------------------------------------------------------------------------------+
```

I found several ways to fix this with [postoverflows whitelist](https://docs.crowdsec.net/docs/whitelist/create/#whitelist-in-postoverflows):

**Normal:**

\# cat /etc/crowdsec/postoverflows/s01-whitelist/whitelist-matrix.yaml (generic) :
```yaml
name: tetsumaki/matrix
description: "custom matrix whitelist"
whitelist:
  reason: "whitelist false positive for matrix"
  expression:
    - evt.Overflow.Alert.Events[0].GetMeta('http_path') startsWith Lower('/_matrix/')
    - evt.Overflow.Alert.GetScenario() == 'crowdsecurity/http-probing'
```

\# cat /etc/crowdsec/postoverflows/s01-whitelist/whitelist-matrix.yaml (target_fqdn) :
```yaml
name: tetsumaki/matrix
description: "custom matrix whitelist"
whitelist:
  reason: "whitelist false positive for matrix"
  expression:
    - evt.Overflow.Alert.Events[0].GetMeta('target_fqdn') == 'matrix.domain.tld'
    - evt.Overflow.Alert.GetScenario() == 'crowdsecurity/http-probing'
```

\# cat /etc/crowdsec/postoverflows/s01-whitelist/whitelist-matrix.yaml (datasource_path) :
```yaml
name: tetsumaki/matrix
description: "custom matrix whitelist"
whitelist:
  reason: "whitelist false positive for matrix"
  expression:
    - evt.Overflow.Alert.Events[0].GetMeta('datasource_path') == '/var/lib/caddy/log/matrix.domain.tld.log'
    - evt.Overflow.Alert.GetScenario() == 'crowdsecurity/http-probing'
```

**Or more aggressive:**

\# cat /etc/crowdsec/postoverflows/s01-whitelist/whitelist-matrix.yaml (generic) :
```yaml
name: tetsumaki/matrix
description: "custom matrix whitelist"
whitelist:
  reason: "whitelist false positive for matrix"
  expression:
    - evt.Overflow.Alert.Events[0].GetMeta('http_path') startsWith Lower('/_matrix/')
    - evt.Overflow.Alert.GetScenario() in ['crowdsecurity/http-probing', 'crowdsecurity/http-probing']
```

\# cat /etc/crowdsec/postoverflows/s01-whitelist/whitelist-matrix.yaml (target_fqdn) :
```yaml
name: tetsumaki/matrix
description: "custom matrix whitelist"
whitelist:
  reason: "whitelist false positive for matrix"
  expression:
    - evt.Overflow.Alert.Events[0].GetMeta('target_fqdn') == 'matrix.domain.tld'
    - evt.Overflow.Alert.GetScenario() in ['crowdsecurity/http-probing', 'crowdsecurity/http-probing']
```

\# cat /etc/crowdsec/postoverflows/s01-whitelist/whitelist-matrix.yaml (datasource_path) :
```yaml
name: tetsumaki/matrix
description: "custom matrix whitelist"
whitelist:
  reason: "whitelist false positive for matrix"
  expression:
    - evt.Overflow.Alert.Events[0].GetMeta('datasource_path') == '/var/lib/caddy/log/matrix.domain.tld.log'
    - evt.Overflow.Alert.GetScenario() in ['crowdsecurity/http-probing', 'crowdsecurity/http-probing']
```
