### ISSUE TITLE
scenario/http-probing on same site but different port 80 and 443

### ISSUE THREAD

**Issue by ririsoft** [crowdsecurity/hub#57]
Hello,

`scenario/http-probing` is grouping by `"evt.Meta.source_ip + '/' + evt.Parsed.target_fqdn"` .
In my logs I noticed the following:

```
127.0.0.1:80 172.105.13.165 - - [25/Nov/2020:07:26:05 +0100] "HEAD / HTTP/1.1" 403 232 160 180 "-" "Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9a3pre) Gecko/20070330"
127.0.0.1:443 172.105.13.165 - - [25/Nov/2020:07:26:05 +0100] "GET /nmaplowercheck1606285565 HTTP/1.1" 403 4218 739 360 "-" "\"Mozilla/5.0"
127.0.0.1:443 172.105.13.165 - - [25/Nov/2020:07:26:06 +0100] "GET /evox/about HTTP/1.1" 403 4218 725 425 "-" "\"Mozilla/5.0"
127.0.0.1:80 172.105.13.165 - - [25/Nov/2020:07:26:09 +0100] "HEAD / HTTP/1.1" 403 232 121 447 "-" "\"Mozilla/5.0"
127.0.0.1:443 172.105.13.165 - - [25/Nov/2020:07:26:42 +0100] "HEAD / HTTP/1.1" 403 3906 755 449 "-" "Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9a3pre) Gecko/20070330"
127.0.0.1:80 172.105.13.165 - - [25/Nov/2020:07:26:48 +0100] "GET / HTTP/1.1" 403 543 120 350 "-" "\"Mozilla/5.0"
127.0.0.1:80 172.105.13.165 - - [25/Nov/2020:07:26:50 +0100] "GET / HTTP/1.0" 403 527 36 233 "-" "-"
127.0.0.1:80 172.105.13.165 - - [25/Nov/2020:07:26:50 +0100] "GET / HTTP/1.1" 403 524 75 333 "-" "-"
127.0.0.1:80 172.105.13.165 - - [25/Nov/2020:07:26:51 +0100] "POST /sdk HTTP/1.1" 403 543 586 406 "-" "\"Mozilla/5.0"
127.0.0.1:443 172.105.13.165 - - [25/Nov/2020:07:26:52 +0100] "POST /sdk HTTP/1.1" 403 4218 1181 413 "-" "\"Mozilla/5.0"
```

The guy is clearly probing my web server but alternates between port 80 and port 443.
What about grouping by `host` instead of `fqdn` ? It looks better for security and I am not sure it will increase the false positive cases. What do you think ?

Cheers.

**Comment by AlteredCoder** [comment]
Hello @ririsoft ,

If i understand correctly the issue, you would preferer to `groupby` `ip:port` instead of only `ip` ?

Cheers.

**Comment by ririsoft** [comment]
Hello @AlteredCoder ,

Grouping by `ip` is totally fine. I would prefer a grouping by `"evt.Meta.source_ip + '/' + %HOST%`.
But looking further into this I believe the issue is on my side, sorry.
Indeed I have a custom apache log parsing:

```yaml
#/etc/crowdsec/config/parsers/s01-parse/apache2-logs.yaml
#Apache access logs
#debug: true
filter: "evt.Parsed.program startsWith 'apache2'"
onsuccess: next_stage
name: crowdsecurity/apache2-logs
description: "Parse Apache2 access and error logs"
#log line can be prefixed by a target_fqdn
grok:
  #pattern: '(%{IPORHOST:target_fqdn} )?%{COMMONAPACHELOG} %{QS:referrer} %{QS:agent}'
  pattern: '(%{URIHOST:target_fqdn} )?%{COMMONAPACHELOG} %{POSINT} %{POSINT} %{QS:referrer} %{QS:agent}'
  apply_on: message
# these ones apply for both grok patterns
statics:
  - meta: log_type
    value: http_access-log
  - target: evt.StrTime
    expression: evt.Parsed.timestamp
  - meta: service
    value: http
  - meta: source_ip
    expression: evt.Parsed.clientip
  - meta: http_status
    expression: evt.Parsed.response
  - meta: http_path
    expression: evt.Parsed.request
```

I needed to have this to catch the port part with the IP, which is not caugh by the partern `%{IPORHOST:target_fqdn}` used by crowdsec by default. However my pattern aggregate the IP and PORT together in the target fqdn which is a mistake. I am going to replace it with something else like `%{IPORHOST:target_fqdn}(?::%{POSINT:port})?`.

I am closing this, since this is due to my personal settings. I am really sorry for the false issue :(
