### ISSUE TITLE
Request: add file browser file previews to the Nextcloud whitelist

### ISSUE THREAD

**Issue by bdcarr** [crowdsecurity/hub#627]
The [Nextcloud whitelist collection](https://github.com/crowdsecurity/hub/pull/609) was created to work around an issue in the [Contacts](https://github.com/nextcloud/contacts/issues/3021) and [Photos](https://github.com/nextcloud/photos/issues/1257) apps in Nextcloud. I've just learned that the same issue occurs in the Files app - probably anywhere a file preview is loaded really.

I just banned myself while searching for files by clicking 'load more' a couple of times with XML files in the search results:

![image](https://user-images.githubusercontent.com/1940488/210563018-d6d82e41-795c-4f9f-83bb-7c2b6b29a864.png)

An example request URL is `https://nextcloud.mydomain.com/core/preview?x=32&y=32&fileId=60489`. I might have a crack at updating the whitelist parser & tests sometime in the next few days, but I'm logging this issue in case I forget or don't have time.

**Comment by LaurenceJJones** [comment]
I added some extra stuff since you linked PR, I appended a potential fix but some logs / tests will be useful before committing a PR
```
name: crowdsecurity/nextcloud-whitelist
description: "Whitelist events from nextcloud"
filter: "evt.Meta.service == 'http' && evt.Meta.log_type in ['http_access-log', 'http_error-log']"
whitelist:
  reason: "Nextcloud Whitelist"
  expression:
   - evt.Meta.http_status == '404' && evt.Meta.http_verb == 'GET' && evt.Parsed.file_ext == '.vcf' && evt.Parsed.http_args contains "photo" #Contacts app .vcf missing photo
   - evt.Meta.http_status == '404' && evt.Meta.http_verb == 'GET' && evt.Meta.http_path contains '/apps/files_versions/preview' && evt.Parsed.http_args contains 'version' #Backup app missing file version
   - evt.Meta.http_status == '404' && evt.Meta.http_verb == 'GET' && evt.Meta.http_path contains '/apps/photos/api/v1/preview' && evt.Parsed.http_args contains 'x' && evt.Parsed.http_args contains 'y' #Photo app loads all previews as small panes, but can 404
   - evt.Meta.http_status == '404' && evt.Meta.http_verb == 'GET' && evt.Meta.http_path contains '/core/preview' && evt.Parsed.http_args contains 'x' && evt.Parsed.http_args contains 'y' #File preview, but can 404
```
