### ISSUE TITLE
opnsense log parsing with the pf-log parser

### ISSUE THREAD

**Issue by a1ad** [crowdsecurity/hub#677]
Hi I am tryring to parse the opnsense logs with this collection: https://hub.crowdsec.net/author/firewallservices/collections/pf

I just do not understand the pf-log parser from the collection.

So the parser is:
```

pattern_syntax:
  PF_UDP_DATA: '%{INT:src_port},%{INT:dst_port},%{INT:data_length}'
  PF_TCP_DATA: '%{PF_UDP_DATA},%{WORD:tcp_flags},%{INT:sequence_number},%{INT:ack_number},%{INT:tcp_window},%{DATA:urg_data},%{DATA:tcp_options}'
  PF_PROTOCOL_DATA: '(%{PF_TCP_DATA}|%{PF_UDP_DATA})'
  PF_IP_DATA: '%{INT:length},%{IP:src_ip},%{IP:dst_ip},'
  PF_IPv4_DATA: '%{BASE16NUM:ip4_tos},,%{INT:ip4_ttl},%{INT:ip4_id},%{INT:ip4_offset},%{WORD:ip4_flags},%{INT:ip4_proto_id},%{WORD:ip4_proto},'
  PF_IPv6_DATA: '%{BASE16NUM:ip6_class},%{DATA:ip6_flow_label},%{INT:ip6_hop_limit},%{WORD:ip6_proto},%{INT:ip6_proto_id},'
  PF_IP_SPECIFIC_DATA: '(%{PF_IPv4_DATA}|%{PF_IPv6_DATA})'
  PF_LOG_DATA: '%{INT:rule},(%{INT:sub_rule})?,,%{INT:tracker},%{DATA:iface},%{WORD:reason},%{WORD:action},%{WORD:direction},%{INT:ip_ver},'
  PF_FILTERLOG: '%{PF_LOG_DATA}%{PF_IP_SPECIFIC_DATA}%{PF_IP_DATA}%{PF_PROTOCOL_DATA}'
grok:
  pattern: "%{PF_FILTERLOG}"
  apply_on: message
```

 And this is working with the pfsense log sample data like this:

`Sep 28 10:38:09 pfSense filterlog: 53,,,1000000301,em0,match,block,in,4,0x0,,64,420,0,none,6,tcp,460,10.0.2.2,10.0.2.15,53742,22,420,PA,29633380:29633800,3617062173,65535,,`

But not working with the opsense log data like this:

`"Mar  1 09:34:39 DMZ-Firewall.int.cvovolt.be filterlog[70440]: 6,,,02f4bab031b57d1e30553ce08e0ec131,em0,match,block,in,4,0x0,,48,11290,0,DF,6,tcp,60,120.78.230.195,193.190.240.10,35024,6379,0,S,193297189,,64240,,mss;sackOK;TS;nop;wscale`

Can we make the pf-log parser compatible for opnsense or do we need to make a new opnsense-pf-log parser?

I tried to search where the parser is getting stuck by modifying the opnsense log without success.

-------------------------------

@LaurenceJJones already did some work for the opnsense parser on Discord, but I am not a fan of the Discord channel, so I hope we can finish the work here on github.

So, I tested the parser for opnsense and combined the pfsense and opnsense in one parser. My live test on 2 opnsense boxes iare running for 2 weeks and counting. It is working like a dream. But I can't test the pfsense part and I don't know if I did the pf and opnsense merge like it should.

New PF parser:

#############################################################################################

```
filter: "evt.Parsed.program == 'filterlog' or evt.Parsed.message matches '^filterlog:'"
name: firewallservices/pf-logs
description: "Parse packet filter logs"
format: 2.0
pattern_syntax:
#common syntax for pfsense/opnsense
 
  PF_UDP_DATA: '%{INT:src_port},%{INT:dst_port},%{INT:data_length}'
  PF_IP_DATA: '%{INT:length},%{IP:src_ip},%{IP:dst_ip},'
  PF_IPv4_DATA: '%{BASE16NUM:ip4_tos},,%{INT:ip4_ttl},%{INT:ip4_id},%{INT:ip4_offset},%{WORD:ip4_flags},%{INT:ip4_proto_id},%{WORD:ip4_proto},'
  PF_IPv6_DATA: '%{BASE16NUM:ip6_class},%{DATA:ip6_flow_label},%{INT:ip6_hop_limit},%{WORD:ip6_proto},%{INT:ip6_proto_id},'
  PF_IP_SPECIFIC_DATA: '(%{PF_IPv4_DATA}|%{PF_IPv6_DATA})'
 
#pf specific
  PF_TCP_DATA: '%{PF_UDP_DATA},%{WORD:tcp_flags},%{INT:sequence_number},%{INT:ack_number},%{INT:tcp_window},%{DATA:urg_data},%{DATA:tcp_options}'
  PF_PROTOCOL_DATA: '(%{PF_TCP_DATA}|%{PF_UDP_DATA})'
  PF_LOG_DATA: '%{INT:rule},(%{INT:sub_rule})?,,%{INT:tracker},%{DATA:iface},%{WORD:reason},%{WORD:action},%{WORD:direction},%{INT:ip_ver},'
  PF_FILTERLOG: '%{PF_LOG_DATA}%{PF_IP_SPECIFIC_DATA}%{PF_IP_DATA}%{PF_PROTOCOL_DATA}'
 
#opnsense specific
  oPF_TCP_DATA: '%{WORD:tcp_flags},%{INT:sequence_number}(,%{INT:ack_number},%{INT:tcp_window},%{DATA:urg_data},%{DATA:tcp_options})?'
  oPF_PROTOCOL_DATA: '%{PF_UDP_DATA}(${oPF_TCP_DATA})?'
  oPF_LOG_DATA: '%{INT:rule},(%{INT:sub_rule})?,,%{DATA:tracker},%{DATA:iface},%{WORD:reason},%{WORD:action},%{WORD:direction},%{INT:ip_ver},'
  oPF_FILTERLOG: '%{oPF_LOG_DATA}%{PF_IP_SPECIFIC_DATA}%{PF_IP_DATA}%{oPF_PROTOCOL_DATA}'
 
nodes:
  - grok:
      pattern: "%{PF_FILTERLOG}"
      apply_on: message
  - grok:
      pattern: "%{oPF_FILTERLOG}"
      apply_on: message
 
statics:
  - meta: log_type
    value: pf
---
filter: "evt.Meta.log_type == 'pf' and evt.Parsed.action == 'block'"
name: firewallservices/pf-logs-drop
description: "Identify dropped packets"
onsuccess: next_stage
statics:
  - meta: service
    value: tcp
  - meta: log_type
    value: pf_drop
  - meta: source_ip
    expression: "evt.Parsed.src_ip"
```

#############################################################################################

Explain output:

pfsense:

```
root@fw:/usr/local/etc/crowdsec/parsers/s01-parse # cscli explain -l "Sep 28 10:38:09 pfSense filterlog: 53,,,1000000301,em0,match,block,in,4,0x0,,64,420,0,none,6,tcp,460,10.0.2.2,10.0.2.15,53742,22,420,PA,29633380:29633800,3617062173,65535,," --type filterlog
line: Sep 28 10:38:09 pfSense filterlog: 53,,,1000000301,em0,match,block,in,4,0x0,,64,420,0,none,6,tcp,460,10.0.2.2,10.0.2.15,53742,22,420,PA,29633380:29633800,3617062173,65535,,
    ├ s00-raw
    |    ├ 🟢 crowdsecurity/non-syslog (first_parser)
    |    └ 🔴 crowdsecurity/syslog-logs
    ├ s01-parse
    |    ├ 🔴 crowdsecurity/opnsense-gui-logs
    |    ├ 🟢 firewallservices/pf-logs (+33)
    |    └ 🟢 firewallservices/pf-logs-drop (+2 ~2)
    ├ s02-enrich
    |    ├ 🔴 crowdsecurity/dateparse-enrich
    |    └ 🟢 crowdsecurity/geoip-enrich (+9)
    ├-------- parser success 🟢
    ├ Scenarios
        └ 🟢 firewallservices/pf-scan-multi_ports
```

and opnsense:

```
root@fw:/usr/local/etc/crowdsec/parsers/s01-parse # cscli explain -l "<134>1 2023-03-03T11:56:07+01:00 fw.protech filterlog 44481 - [meta sequenceId="8180"] 7,,,02f4bab031b57d1e30553ce08e0ec131,igb3,match,block,in,4,0x0,,59,54088,0,DF,6,tcp,60,81.82.208.17,84.192.174.88,40254,3389,0,S,3963160055,,64240,,mss;sackOK;TS;nop;wscale" --type filterlog
line: <134>1 2023-03-03T11:56:07+01:00 fw.protech filterlog 44481 - [meta sequenceId=8180] 7,,,02f4bab031b57d1e30553ce08e0ec131,igb3,match,block,in,4,0x0,,59,54088,0,DF,6,tcp,60,81.82.208.17,84.192.174.88,40254,3389,0,S,3963160055,,64240,,mss;sackOK;TS;nop;wscale
    ├ s00-raw
    |    ├ 🟢 crowdsecurity/non-syslog (first_parser)
    |    └ 🔴 crowdsecurity/syslog-logs
    ├ s01-parse
    |    ├ 🔴 crowdsecurity/opnsense-gui-logs
    |    ├ 🟢 firewallservices/pf-logs (+27)
    |    └ 🟢 firewallservices/pf-logs-drop (+2 ~2)
    ├ s02-enrich
    |    ├ 🔴 crowdsecurity/dateparse-enrich
    |    └ 🟢 crowdsecurity/geoip-enrich (+13)
    ├-------- parser success 🟢
    ├ Scenarios
        └ 🟢 firewallservices/pf-scan-multi_ports
```

The parses can be installed on the opsense box itself, we do not need to remote syslog like on pfSense.

You just need to install the crowdsec plugin in the GUI, config it like you want and install the pf collection through the cli like this:
`cscli collections install firewallservices/pf`
Add a new acquis file in:
vi /usr/local/etc/crowdsec/acquis.d/a1ad.yaml
With:

```
filenames:
 # filterlog
 - /var/log/filter/latest.log
labels:
  type: syslog
```
Replace the pf parser with the one from here and restart the service.

The default scenario: firewallservices/pf-scan-multi_ports is working, but I am also using 2 custom-made scenarios:

pf-slow-bf.yaml

```
type: leaky
name: a1ad/pf-slow-bf
description: "ban IPs that are slowly scanning us or trying to BF one port ONLY ON THE WAN //change WAN IF to yours"
filter: "evt.Meta.log_type == 'pf_drop' && evt.Meta.service == 'tcp' && evt.Parsed.iface == 'igb3'"
groupby: evt.Meta.source_ip
capacity: 4
leakspeed: 1m
blackhole: 1m
#reprocess: true
labels:
  service: tcp
  type: bruteforce
  remediation: true
```

And a very aggressive one: pf-detect-blocked.yaml, but I would not recommend this in a production environment. This one blocks all the IPs that are going through my opnsense blocklist (fireholl lvl 1,2,3) and geoblock list. I only have port 443 open, so every hit on a different port is getting blocked.

```
type: trigger
name: a1ad/pf-detect-blocked
description: "ban IPs that are hitting a blocked port on WAN"
filter: "evt.Meta.log_type == 'pf_drop' && evt.Meta.service == 'tcp' && evt.Parsed.iface == 'igb3'"
groupby: evt.Meta.source_ip
labels:
  service: tcp
  type: bruteforce
  remediation: true
```

So, I am very happy with the setup and I guess it could benefit other too. I would be great to have the parser in the public hub. I can create a PR i you want but:
1. The parser is the work of @LaurenceJJones, i don't want to take credit for it.
2. I don't know if my combine action is like it should.

Regards,
a1aD
