### ISSUE TITLE
false positive bad user agent : screaming frog

### ISSUE THREAD

**Issue by Greg4040** [crowdsecurity/hub#681]
Hi,
SEO company use https://www.screamingfrog.co.uk/seo-spider/ and Crowdsec ban them.

grep -i screaming /var/lib/crowdsec/data/bad_user_agents.regex.txt 
->
\bScreaming\b

**Comment by Greg4040** [comment]
Yes of course, 

But why not ban Semrush crawler who : 
- Continual request server even after the SEO company work
- has an option to impersonate google's robot

Customer call me for that and I have to white list their IP (temp solution).
Semrush or screaming frog are paid tools. Not sure if it is realy used for bad think. Never seen that and i pass my time on apache logs.

A friend told me to do that : 
in /etc/crowdsec/parsers/s02-enrich/
->
```
name: si/whitelist-screaming-frog
description: "Whitelist access on user agent Screaming Frog SEO Spider"
whitelist:
  reason: "Access from Screaming Frog SEO Spider"
  expression:
    - "evt.Meta.log_type == 'http_access-log' && evt.Parsed.http_user_agent contains 'Screaming Frog SEO Spider'"
```
I haven't tested yet.

Thank for your awesome solution.

PS : sorry for my poor english, French natural language here
