### ISSUE TITLE
Express-winston log parser

### ISSUE THREAD

**Issue by LaurenceJJones** [crowdsecurity/hub#768]
In most "cases" a user will use a reverse proxy for nodejs applications.  However, a user may just not a bind nodejs to 80,443, in this case we may want to support some loggers provided to nodejs ecosystem:

[Winston](https://www.npmjs.com/package/express-winston) was my and many go to express logger. It support JSON as well as text so these both must be covered to have successful parser. We should format the `Parsed` and `Meta` attributes so it works with http-base scenarios.

**We must make it clear if they have a reverse proxy they do not also need to set this up**

**Comment by LaurenceJJones** [comment]
My idea was to have a single parser for "express" or "javascript" then we can use filters to provided context to groks.

```yaml
name: crowdsecurity/javascript
filter: evt.Parsed.program startsWith 'javascript'
...
nodes:
  - filter: evt.Parsed.program startsWith 'morgan'
    grok:
     ...
  - filter: evt.Parsed.program startsWith 'winston'
    grok:
     ...
statics:
 .... normalise statics from all parsers
 ```
