### ISSUE TITLE
Caddy Log Parser : client ip is not parsed

### ISSUE THREAD

**Issue by SimonVanacco** [crowdsecurity/hub#995]
The IP address of the client is not parsed by the Caddy log parser. 

Here is an example log created today with Caddy (version 2.6.2) : 

```
{"level":"info","ts":1709920868.9599843,"logger":"http.log.access.log0","msg":"handled request","request":{"remote_ip":"X.X.X.X","remote_port":"10251","proto":"HTTP/1.1","method":"HEAD","host":"myhost.fr","uri":"/.env","headers":{"User-Agent":[
"curl/8.2.1"],"Accept":["*/*"]}},"user_id":"","duration":0.000049745,"size":0,"status":308,"resp_headers":{"Server":["Caddy"],"Connection":["close"],"Location":["https://myhost.fr/.env"],"Content-Type":[]}}
```

As you can see the client IP is located in the key **request.remote_ip**, however in the parser file contains this instead 
```yaml
# /etc/crowdsec/parsers/s01-parse/caddy-logs.yaml
  - parsed: remote_ip
    expression: evt.Unmarshaled.caddy.request.client_ip
```

**This means that any event happening won't have a related ip address to ban** (confirmed with cscli explained). Is there something i messed up in the configuration ? 

Here is my Caddyfile : 

```
myhost.fr {
        root * /var/www/myhost/public/
        encode gzip
        log {
                output file /var/log/caddy/access_myhost.log
        }
        php_fastcgi unix//run/php/php8.3-fpm.sock
        file_server
}
```

And my acquis.yaml : 

```yaml
journalctl_filter:
 - _SYSTEMD_UNIT=ssh.service
labels:
  type: syslog
---
filenames:
 - /var/log/caddy/*.log
labels:
  type: caddy
---
```
